In [53]:
import time
lista = list(range(1000000))
inicio = time.time()
[valor * 2 for valor in lista]
print("Tiempo de ejecucion con listas", time.time()-inicio)

Tiempo de ejecucion con listas 0.11742138862609863


In [54]:
import numpy as np
arreglo = np.arange(1000000)
inicio = time.time()
arreglo * 2
print("Tiempo de ejecucion con listas", time.time() - inicio)

Tiempo de ejecucion con listas 0.0024764537811279297


In [55]:
!pip install numpy

In [56]:
import numpy as np
arreglo = np.array([1,2,3,4], dtype = float)
print(arreglo)

[1. 2. 3. 4.]


In [57]:
print("El numero de dimensiones del arreglo son: ", arreglo.ndim)
print("La forma del arreglo es ", arreglo.shape)
print("El total de elementos en el arreglo son: ", arreglo.size)
print("Los tipos de datos en el arreglo son: ", arreglo.dtype) #Entre mas grande el numero mas cantidad de datos puede almacenar

El numero de dimensiones del arreglo son:  1
La forma del arreglo es  (4,)
El total de elementos en el arreglo son:  4
Los tipos de datos en el arreglo son:  float64


In [58]:
arreglo_2d = np.array([[1,2,3], [4,5,6]], dtype = float)
print(arreglo_2d)

[[1. 2. 3.]
 [4. 5. 6.]]


In [59]:
print("El numero de dimensiones del arreglo son: ", arreglo_2d.ndim)
print("La forma del arreglo es ", arreglo_2d.shape)
print("El total de elementos en el arreglo son: ", arreglo_2d.size)
print("Los tipos de datos en el arreglo son: ", arreglo_2d.dtype)

El numero de dimensiones del arreglo son:  2
La forma del arreglo es  (2, 3)
El total de elementos en el arreglo son:  6
Los tipos de datos en el arreglo son:  float64


In [60]:
arreglo_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arreglo_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
print("El numero de dimensiones del arreglo son: ", arreglo_3d.ndim)
print("La forma del arreglo es ", arreglo_3d.shape)
print("El total de elementos en el arreglo son: ", arreglo_3d.size)
print("Los tipos de datos en el arreglo son: ", arreglo_3d.dtype)

El numero de dimensiones del arreglo son:  3
La forma del arreglo es  (2, 2, 3)
El total de elementos en el arreglo son:  12
Los tipos de datos en el arreglo son:  int64


In [62]:
ceros = np.zeros((2,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
vacio = np.empty((6,5))
vacio

array([[4.90138380e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 4.00193173e-322, 4.90188638e-315,
        6.69326912e-310, 4.88699611e-315],
       [6.69326912e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [65]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [66]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [67]:
np.random.rand(2,3,1)

array([[[0.39559794],
        [0.03421876],
        [0.90383913]],

       [[0.19189709],
        [0.99975526],
        [0.33448938]]])

In [68]:
arreglo1 = np.array([[1,0], [-1,1]])
arreglo1

array([[ 1,  0],
       [-1,  1]])

In [69]:
arreglo1 / 0

/tmp/ipykernel_535/1539411815.py:1: RuntimeWarning: divide by zero encountered in divide
  arreglo1 / 0
/tmp/ipykernel_535/1539411815.py:1: RuntimeWarning: invalid value encountered in divide
  arreglo1 / 0


array([[ inf,  nan],
       [-inf,  inf]])

In [70]:
0 / arreglo1

/tmp/ipykernel_535/1581917867.py:1: RuntimeWarning: invalid value encountered in divide
  0 / arreglo1


array([[ 0., nan],
       [-0.,  0.]])

In [71]:
arreglo2 = np.array([[np.inf, np.nan], [1,2]])
arreglo2

array([[inf, nan],
       [ 1.,  2.]])

In [72]:
array_inf = np.array([1, 2.5])**25 #entre mas grande se eleve, python lo considerara como infinito
array_inf

array([1.0000000e+00, 8.8817842e+09])