In [1]:
import numpy as np

In [12]:
brigadas = np.array([[['Juan', 'Alex', 'Antonio'], ['Arturo', 'Valentina', 'Vanessa']],
                     [['Ricardo', 'Felipe', 'Paola'], ['Marco', 'Jorge', 'Alejandro']],
                     [['Esteban', 'Ramiro', 'Antonio'], ['Sara', 'Camila', 'Emily']],
                     [['Arley', 'Andrea', 'Alejandra'], ['Maria', 'Angel', 'Jesus']],
                     [['Emmanuel', 'Nelson', 'Fabian'], ['Sarai', 'Camilo', 'Emely']]])
print(brigadas)

[[['Juan' 'Alex' 'Antonio']
  ['Arturo' 'Valentina' 'Vanessa']]

 [['Ricardo' 'Felipe' 'Paola']
  ['Marco' 'Jorge' 'Alejandro']]

 [['Esteban' 'Ramiro' 'Antonio']
  ['Sara' 'Camila' 'Emily']]

 [['Arley' 'Andrea' 'Alejandra']
  ['Maria' 'Angel' 'Jesus']]

 [['Emmanuel' 'Nelson' 'Fabian']
  ['Sarai' 'Camilo' 'Emely']]]


In [13]:
brigadas.ndim

3

In [14]:
brigadas.shape

(5, 2, 3)

In [15]:
brigadas[1:3,:,:]

array([[['Ricardo', 'Felipe', 'Paola'],
        ['Marco', 'Jorge', 'Alejandro']],

       [['Esteban', 'Ramiro', 'Antonio'],
        ['Sara', 'Camila', 'Emily']]], dtype='<U9')

In [16]:
brigadas[:, 1, 0:2]

array([['Arturo', 'Valentina'],
       ['Marco', 'Jorge'],
       ['Sara', 'Camila'],
       ['Maria', 'Angel'],
       ['Sarai', 'Camilo']], dtype='<U9')

In [17]:
brigadas[:, 1, 0:2]

array([['Arturo', 'Valentina'],
       ['Marco', 'Jorge'],
       ['Sara', 'Camila'],
       ['Maria', 'Angel'],
       ['Sarai', 'Camilo']], dtype='<U9')

In [18]:
type(brigadas[:, 1, 0:2])

numpy.ndarray

In [19]:
sustitutos = np.array([['John', 'Ringo', 'Paul'],
                       ['Keith', 'Mick', 'Charlie']])

In [20]:
sustitutos.shape

(2, 3)

In [21]:
brigadas[4,:,:] = 'sustitutos'

In [22]:
brigadas[1,1,:] = ['parcifal', 'Gawain', 'Lancelot']

In [23]:
brigadas[4,1,2] = 'Pascual'

In [24]:
matriz_1 = np.array([[1,2,3], [4,0,-5], [-6,-7,-8]])

In [25]:
matriz_1 + 100

array([[101, 102, 103],
       [104, 100,  95],
       [ 94,  93,  92]])

In [26]:
matriz_1[2,:] *3

array([-18, -21, -24])

In [27]:
3 / matriz_1

/tmp/ipykernel_7671/113740686.py:1: RuntimeWarning: divide by zero encountered in divide
  3 / matriz_1


array([[ 3.        ,  1.5       ,  1.        ],
       [ 0.75      ,         inf, -0.6       ],
       [-0.5       , -0.42857143, -0.375     ]])

In [28]:
matriz_1 / 2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  0. , -2.5],
       [-3. , -3.5, -4. ]])

In [29]:
matriz_1 > 1

array([[False,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [30]:
matriz_1 < 1

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [31]:
matriz_1.shape

(3, 3)

In [32]:
matriz_2 = np.array([1,2,3])

In [33]:
matriz_2.shape

(3,)

In [34]:
matriz_1 * matriz_2

array([[  1,   4,   9],
       [  4,   0, -15],
       [ -6, -14, -24]])

In [35]:
matriz_3 = np.array([[2], [4], [6]])

In [36]:
matriz_3

array([[2],
       [4],
       [6]])

In [37]:
matriz_3.shape

(3, 1)

In [38]:
matriz_3 * matriz_1

array([[  2,   4,   6],
       [ 16,   0, -20],
       [-36, -42, -48]])

In [39]:
m1 = np.array

Esto no es lo mismo con las operaciones de algebra lineal