In [1]:
import numpy as np
arreglo_2 = np.array([[1,2,3,4],
                      [5,6,7,8],
                      [9,10,11,12]])

In [2]:
arreglo_2.shape

(3, 4)

In [3]:
arreglo_2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [4]:
arreglo_2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [5]:
arreglo_2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
np.reshape(arreglo_2,(1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [7]:
arreglo_3 = np.array([[1,2],
                      [3,4]])

In [8]:
arreglo_3.shape

(2, 2)

In [9]:
arreglo_3.resize(3,3,2) #para aumentar la matriz

In [10]:
arreglo_3

array([[[1, 2],
        [3, 4],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [11]:
arreglo_4 = np.array([[1,2],
                      [3,4]])

In [12]:
arreglo_4.shape

(2, 2)

In [13]:
np.resize(arreglo_4, (2,3,2))

array([[[1, 2],
        [3, 4],
        [1, 2]],

       [[3, 4],
        [1, 2],
        [3, 4]]])

In [14]:
matriz = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

In [15]:
matriz.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [16]:
origen = np.arange(9).reshape(3,3,1)

In [17]:
origen

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [18]:
np.squeeze(origen,2)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.squeeze(origen,2).shape

(3, 3)

In [20]:
arreglo_1 = np.array([[1,2],
                      [3,4]])

In [21]:
arreglo_1

array([[1, 2],
       [3, 4]])

In [22]:
arreglo_2 = np.array([[5,6],
                      [7,8]])

In [23]:
np.concatenate((arreglo_1, arreglo_2), 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
np.concatenate((arreglo_1, arreglo_2), axis = 1) #Eje de las colunmas el 1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [25]:
np.concatenate((arreglo_1, arreglo_2), 0) #eje de las filas el 0

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
arreglo_original = np.arange(9).reshape(3,3)

In [27]:
arreglo_original

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arreglo_eje_0 = np.array([[5,6,7], [8,9,10]])

In [29]:
arreglo_eje_0

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [30]:
np.append(arreglo_original, arreglo_eje_0, axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [31]:
arreglo_eje_1 = np.arange(7,13).reshape(3,2)

In [32]:
arreglo_eje_1

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [33]:
np.append(arreglo_original, arreglo_eje_1, axis = 1)

array([[ 0,  1,  2,  7,  8],
       [ 3,  4,  5,  9, 10],
       [ 6,  7,  8, 11, 12]])